swagger:
  show: true
mybatis:
    mapper-locations: classpath:mybatis/mapper/*.xml
    type-aliases-package: com.archerzhang.email.module
    config-location: classpath:mybatis/mybatis-config.xml
spring:
      datasource:
          url: jdbc:mysql://localhost:3306/zdemo?useUnicode=true&characterEncoding=UTF-8
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
      kafka:
            bootstrap-servers: localhost:9092
            producer:
              retries: 0
              batch-size: 16384
              buffer-memory: 33554432
            #      key-serializer: org.apache.kafka.common.serialization.StringSerializer
            #      value-serializer: org.apache.kafka.common.serialization.StringSerializer
            consumer:
              group-id: 0
              auto-commit-interval: 100
              auto-offset-reset: earliest
              enable-auto-commit: true
              key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
              value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            listener:
              concurrency: 3
logging:
    config: classpath:logConf/logback-dev.xml
